services:

  mysql:
    image: mariadb:10.11
    container_name: todo-mysql
    restart: unless-stopped
    command: --skip-ssl
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: tododb
      MARIADB_USER: todouser
      MARIADB_PASSWORD: todopassword
    ports:
      - "3305:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - todo-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
        
    environment:
      # useSSL=false explicitly tells Spring Boot not to look for certificates
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tododb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: todouser
      SPRING_DATASOURCE_PASSWORD: todopassword
      S3_BUCKET_NAME: your-s3-bucket-name
      AWS_REGION: us-east-1
    networks:
      - todo-network

  nginx:
    image: nginx:1.27-alpine
    container_name: todo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge